[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "robust-llm-unlearning"
version = "0.1.0"
description = "Official implementation of Minor Component Unlearning for robust LLM unlearning against relearning attacks"
authors = [
    {name = "Zeguan Xiao"},
    {name = "Xuanzhe Xu"},
    {name = "Yun Chen"},
    {name = "Yong Wang"},
    {name = "Jian Yang"},
    {name = "Yanqing Hu"},
    {name = "Guanhua Chen"},
]
readme = "README.md"
requires-python = ">=3.11"
license = {file = "LICENSE"}
dependencies = [
    "bitsandbytes",
    "datasets",
    "gunicorn",
    "ipykernel",
    "ipywidgets",
    "lm_eval==0.4.8",
    "matplotlib",
    "optuna",
    "optuna-dashboard",
    "peft",
    "scipy",
    "tiktoken",
    "torch",
    "torcheval",
    "transformers",
    "wandb",
    "plotly",
    "nbformat",
    "kaleido",
    "psycopg2-binary",
    "modal",
    "PyYAML",
    "hydra-core",
    "tensordict",
]

classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"
