# root_path: optional local prefix; leave model_id as a HuggingFace repo id to download from the Hub

tags:
  - years
  - llama3.1-8b

# general, unlikely to change
tokenizer:
    max_length: 128
    padding: true
    truncation: true
    return_tensors: pt
train_batch_size: 32  # can be higher because batches are usually shorter
wikitext_batch_size: 16
retain_batch_size: 16
num_eval_batches: 16
target_modules:
  - gate_proj
  - up_proj
  - down_proj

model_id: meta-llama/Llama-3.1-8B

dataset: years
num_examples_per_question: 3
use_dev_split: false

max_num_epochs: 50

retraining_rate: 1e-5  # even with 1e-6, wikitext_loss has this Nike shape
retraining_epochs: 30
eval_on_all_questions: false

# default experiment config
algorithm: CIR
loss_budget: 1.01
cir_niter: 16
comment: null
mask_n_most_common_tokens: null
# mask_n_most_common_tokens: 50
# eval_on_all_questions: true  # best to just use it when not retraining

cut_off_tokens: 1
loss_fn_name: ???
mlp_floor: 0.0
org_out_proj_num: 32

max_norm: ???
act_proj_num: 24
grad_proj_num: 36
layer_range: [6, 12]

# cb_type: dot
cb_type: cossim
cb_floor: 0.0
cb_pow: 1.0
# mlp_retaining_pow: 1.0

# this is used both for CIR and for CB
retaining_rate: 3e-4  # 1e-3 is fine too, but let's be safe and slow
retaining_loss_fns: [cb_retain]
cb_retaining_layers: [12]
cb_retaining_pow: 1.0

retain_on_dev: false
pca_every_n: null
pca_every_steps: 25
pca_cache_size: null  # 74 batches at total, not OOM when pca

rmu_steering_coeff: 1.0
rmu_retaining_layers: [12]

# let's search 3 OOMs, using 9 runs, and a constant low retaining rate
#
# for GA:
# retaining_rate: 1e-5  # 3e-5 is fine too, but let's be safe

experiment_list:
    
    # 0 - CIR BEST
    - loss_fn_name: mlp_confuse
      max_norm: 0.1

    # 1 - CIR + mlp_confuse_mcu
    - loss_fn_name: mlp_confuse_mcu
      max_norm: 0.1

    # 2 - GradDiff
    - loss_fn_name: neg_cross_entropy
      algorithm: GA
      retaining_rate: 1e-5
      retaining_loss_fns: [cross_entropy]
      loss_budget: 1.5
      max_norm: 0.001

    # 3 - RMU + CIR
    - loss_fn_name: rmu
      retaining_loss_fns: [rmu_retain]
      layer_range: [11, 12]
      loss_budget: 1.05
      max_norm: 0.1

    # 4 - RMU + CIR + MCU
    - loss_fn_name: rmu_mcu
      retaining_loss_fns: [rmu_retain]
      layer_range: [11, 12]
      loss_budget: 1.1
      max_norm: 0.1
